#  ----------------------------------------------------------------------------------
#
#  Copyright (c) 2024, NVIDIA CORPORATION. All rights reserved.
#
#  The contents of this file are licensed under the Eclipse Public License 2.0.
#  The full terms of the license are available at https://eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  ----------------------------------------------------------------------------------

SUBDIRS := $(patsubst %/Makefile, %, $(wildcard */Makefile))

GOALS := $(or $(MAKECMDGOALS), all)

.PHONY: $(GOALS) $(SUBDIRS)

$(GOALS): $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -C $@ $(MAKECMDGOALS)
